name: Build on Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: make (default options)
      run: make
    - name: clean
      run: make clean
    - name: make (all classes enabled)
      run: make CFLAGS=-DEMDNS_SUPPORT_ALL_CLASSES
